### ISSUE TITLE
unzip it all

### ISSUE THREAD

**Issue by PhillipSz** [edent/BMW-OpenSource#1]
Or would that be too big? I mean git does compress it anyway, when it's cloned.

**Comment by edent** [comment]
Two of the files were zipped and over GitHub's 100MB per file limit. I have uncompressed those. 

I'd rather keep things exactly as they were provided to me - unless you can give me a compelling case otherwise?

**Comment by homecoded** [comment]
I second @PhillipSz here.

I cannot actually look at the code. I'd need to download the complete repo and extract every tarball to get to the code. I like to casually browse code on Github, which is not possible if tarballed.

You could make two folders: original and uncompressed. This way you still have the original state and a state that can be browsed via GitHub (for lazy people like me). 
... Unless that tickles some repo-size limitation trigger....

**Comment by ndarville** [comment]
I prefer the files to be uploaded as-is. You can always create an unzipped branch, assuming you don’t run into problems with LFS. :)

**Comment by icf20** [comment]
remember to distribute large file you can always talk to [IPFS](https://github.com/ipfs) people here on github

**Comment by edent** [comment]
Sadly, I don't have the bandwidth to upload all this again in an uncompressed format.  Happy to take a Pull Request to a separate branch.
